social/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from social.apps.core.views import (HomeView, ProfileView, FriendsView,
                                    friends_manipulation, profile_edit,
                                    messages_list, message_write,
                                    check_messages, search_friends,
                                    register_user)
from django.contrib.auth.decorators import login_required


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', login_required(HomeView.as_view()), name='home_page'),
    url(r'^login/$', 'social.apps.core.views.custom_login', {
        'template_name':'core/login.html',
    }, name='login_page'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {
        'next_page': '/',
        }, name='logout_page'),
    url(r'^profile/(?P<pk>\d+)/$', login_required(ProfileView.as_view()), name='profile_page'),
    url(r'^profile/edit/$', login_required(profile_edit), name='profile_edit_page'),
    url(r'^friends/$', login_required(FriendsView.as_view()), name='friends_page'),
    url(r'^friends/search/$', search_friends, name='search_friends_page'),
    url(r'^messages/$', messages_list, name='messages_page'),
    url(r'^messages/check/$', check_messages, name='check_messages'),
    url(r'^messages/write/(?P<pk>\d+)/$', message_write, name='message_write_page'),
    url(r'^registration/$', register_user, name='register_page'),
    url(r'^friends_manipulation/$', login_required(friends_manipulation), name='friends_manipulation'),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )


if settings.IS_TESTING:
    urlpatterns += patterns('',
        url(r'^user/(?P<username>[\w@\.+-]+)/$', 'helpers42cc.views.profile',
            name='profile')
    )

social/apps/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class SocialProfile(models.Model):
    user = models.OneToOneField(User)

    avatar = models.ImageField(default='pic.jpg', upload_to='avatars')
    date_of_birth = models.DateField(null=True)
    home_town = models.CharField(max_length=20, blank=True)
    phone_number = models.CharField(max_length=10, blank=True)
    skype_id = models.CharField(max_length=20, blank=True)

    friends = models.ManyToManyField('SocialProfile', blank=True, null=True)

    def __unicode__(self):
        return 'Profile of {} {}'.format(self.user.first_name, self.user.last_name)

    def get_wallposts_received(self):
        return AnyPost.objects.filter(receiver=self, post_type=AnyPost.WALL).order_by('-timestamp')

    def get_new_messages_count(self):
        return AnyPost.objects.filter(receiver=self, post_type=AnyPost.MESSAGE, seen=False).count()


class AnyPost(models.Model):
    MESSAGE = 'message'
    WALL = 'wall'
    POST_TYPES = (
        (MESSAGE, 'Message'),
        (WALL, 'Wall'),
    )

    sender = models.ForeignKey(User, related_name='posts_sent')
    receiver = models.ForeignKey(User, related_name='posts_received')
    text = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(auto_now_add=True)
    post_type = models.CharField(max_length=50, choices=POST_TYPES, default=MESSAGE)
    seen = models.BooleanField(default=False)

    def __unicode__(self):
        return '{} to {} from {} at {}'.format(
            self.post_type,
            self.receiver,
            self.sender,
            self.timestamp,
        )

social/apps/core/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm, HiddenInput, ModelChoiceField, CharField
from django.contrib.auth.models import User

from social.apps.core.models import AnyPost, SocialProfile


# Create the form class.
class WallPostForm(ModelForm):
    sender = ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput, required=False)
    receiver = ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput, required=False)

    class Meta:
        model = AnyPost
        fields = ('text', 'sender', 'receiver')

    def save(self, force_insert=False, force_update=False, commit=True):
        instance = super(WallPostForm, self).save(commit=False)
        instance.post_type = AnyPost.WALL
        if commit:
            instance.save()
        return instance


class ProfileForm(ModelForm):
    name = CharField(max_length=20)
    last_name = CharField(max_length=20)

    class Meta:
        model = SocialProfile
        exclude = ['friends', 'user']

class UserForm(forms.Form):
    username = CharField(max_length=20)
    password = CharField(max_length=35, widget=forms.PasswordInput())


class MessageForm(ModelForm):
    sender = ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput, required=False)
    receiver = ModelChoiceField(queryset=User.objects.all(), widget=HiddenInput, required=False)

    class Meta:
        model = AnyPost
        fields = ('text', 'sender', 'receiver')

    def save(self, force_insert=False, force_update=False, commit=True):
        instance = super(MessageForm, self).save(commit=False)
        instance.post_type = AnyPost.MESSAGE
        if commit:
            instance.save()
        return instance

social/apps/core/views.py
# -*- coding: utf-8 -*-
from annoying.decorators import render_to
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.views import login
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden, Http404, HttpResponse

from social.apps.core.models import SocialProfile, AnyPost
from social.apps.core.forms import WallPostForm, MessageForm
from django.db.models import Q
from social.apps.core.forms import ProfileForm, UserForm
from django.contrib.auth import authenticate, login as log_in
from django.contrib.auth.forms import UserCreationForm


class HomeView(TemplateView):
    template_name = 'core/home.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('profile_page', kwargs={'pk': request.user.get_profile().pk}))
        return None


class ProfileView(DetailView, FormMixin):
    template_name = 'core/profile.html'
    model = SocialProfile
    form_class = WallPostForm

    def get_success_url(self):
        return reverse('profile_page', kwargs={'pk': self.get_object().pk})

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context['form'] = form

        wallposts = self.object.get_wallposts_received()
        context['wallposts'] = wallposts
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            post = form.save(commit=False)
            post.receiver = self.get_object().user
            post.sender = request.user
            post.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def profile_edit(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.get_profile())
        if form.is_valid():
            form.save()

            request.user.first_name = form.cleaned_data['name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()

            return redirect(reverse('profile_page', kwargs={'pk': request.user.get_profile().pk}))
        else:
            return render(request, 'core/profile_edit.html', {'form': form})

    form = ProfileForm(
        instance=request.user.get_profile(),
        initial={
            'name': request.user.first_name,
            'last_name': request.user.last_name,
            }
    )
    return render(request, 'core/profile_edit.html', {'form': form})


def register_user(request):
    if request.user.is_authenticated and not request.user.is_anonymous:
        return redirect(reverse('profile_page', kwargs={'pk': request.user.get_profile().pk}))
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            SocialProfile.objects.create(user=user)
            user.first_name = user.username
            user.save()

            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            if user:
                log_in(request, user)
            return redirect(reverse('profile_edit_page'))
        else:
            return render(request, 'core/register.html', {'form': form})

    form = UserCreationForm()
    return render(request, 'core/register.html', {'form': form})



class FriendsView(ListView):
    template_name = 'core/friends_list.html'
    model = SocialProfile
    context_object_name = 'friends'

    def get_context_data(self, **kwargs):
        context = super(FriendsView, self).get_context_data(**kwargs)
        context['friends'] = self.request.user.get_profile().friends.all
        return context

@login_required
@render_to('core/messages_list.html')
def messages_list(request):
    messages = AnyPost.objects.filter(
        post_type=AnyPost.MESSAGE,
    )
    messages = messages.filter(
        Q(receiver=request.user) |
        Q(sender=request.user)
    ).order_by('seen', '-timestamp')
    messages.filter(receiver=request.user).update(seen=True)
    return {
        'messages': messages[:50],
    }

@login_required
@render_to('core/message_write.html')
def message_write(request, pk):
    friend = User.objects.get(pk=pk)

    if not friend.get_profile() in request.user.get_profile().friends.all():
        raise Http404

    form = MessageForm(request.POST or None)
    if form.is_valid():
        message = form.save(commit=False)
        message.receiver = friend
        message.sender = request.user
        message.save()
        return redirect(reverse('messages_page'))

    return {
        'form': form,
        'friend': friend,
    }

@login_required
@render_to('core/search_friends.html')
def search_friends(request):
    found = None
    q = request.GET.get('q', None)
    if q:
        found = User.objects.filter(
            Q(first_name__icontains=q) |
            Q(last_name__icontains=q)
        ).order_by('first_name').exclude(pk=request.user.pk)[:10]

    return {
        'found': found,
        'q': q,
    }

def custom_login(request, **kwargs):
    if request.user.is_authenticated():
        return redirect('/', **kwargs)
    else:
        return login(request, **kwargs)


@require_POST
def friends_manipulation(request):
    if request.POST.get('add'):
        #Adding a friend
        request.user.get_profile().friends.add(SocialProfile.objects.get(pk=request.POST["pk"]))
        return redirect(reverse('home_page'))

    if request.POST.get('remove'):
        #Adding a friend
        request.user.get_profile().friends.remove(SocialProfile.objects.get(pk=request.POST["pk"]))
        return redirect(reverse('home_page'))

@csrf_exempt
@require_POST
def check_messages(request):
    if request.POST.get('user_pk'):
        user = User.objects.get(pk=request.POST.get('user_pk'))
        return HttpResponse(user.get_profile().get_new_messages_count())
    raise HttpResponseForbidden

social/apps/core/templates/core/friends_list.html
{% extends 'base.html' %}
{% block head_title %}
    Friends list
{% endblock head_title  %}
{% block content %}
    {% if not friends %}
        <h3>Oh gush! <a href="{% url 'search_friends_page' %}">Find some friends</a></h3>
    {% endif %}
    {% for friend in friends %}
<div class="row-fluid">
    <div class="span4">
        <img src="{{ MEDIA_URL }}/{{ friend.avatar }}" class="img-polaroid">
    </div>
    <div class="offset1 span7">
        <p><a href="{% url 'profile_page' friend.pk %}"><h4>{{ friend.user.first_name }} {{ friend.user.last_name }}</h4></a></p>
        <p>Born at: {{ friend.date_of_birth }}</p>
        <p>Home town: {{ friend.home_town }}</p>
        <form  action="{% url 'friends_manipulation' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{ friend.pk }}">
            <input type="submit" class="btn btn-danger" name="remove" value="Remove friend">
        </form>
    </div>
 </div>
        <br/><br/>
    {% endfor %}

{% endblock content %}

social/apps/core/templates/core/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block head_title %}
    Home
{% endblock head_title  %}
{% block home_active %}active{% endblock %}

{% block content %}
{% trans "Your template project is landed here!" %}

{% endblock content %}

social/apps/core/templates/core/login.html
{% extends 'base.html' %}

{% block head_title %}Sign In{% endblock %}

{% block extra_head_js %}
        <script src="{{ STATIC_URL }}/js/login.js"></script>
{% endblock %}

{% block content %}

<legend>Please, Sign In!</legend>
{%if form.errors %}
<div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    Invalid username/password combination, please try again!
</div>
{% endif %}
<form action="{% url 'login_page' %}" method="POST" class="form-horizontal">
    {% csrf_token %}
    <div class="control-group">
        <label class="control-label">{{form.username.label_tag}}</label>
        <div class="controls">{{form.username}}</div>
    </div>
    <div class="control-group">
        <label class="control-label">{{form.password.label_tag}}</label>
        <div class="controls">{{form.password}}</div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input class="btn btn-primary" type="submit" id="submit" name="submit" value="Sign in" />
            <input type="hidden" name="next" value="/" />
            or <a href="{% url 'register_page' %}">Sign Up</a> if you don't have account!
        </div>
    </div>
</form>

{% endblock content %}

social/apps/core/templates/core/message_write.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}Send a message{% endblock %}

{% block content %}
    <h4>Composing a message</h4><br>
    for <a href="{% url 'profile_page' friend.pk %}">
        {{ friend.first_name }} {{ friend.last_name }}
    </a>
    <form action="" method="post">
        {% csrf_token %}
        <p><label id_for="id_text">Message body:</label>
        <p><textarea class="input-block-level" id="id_text" name="text" rows="4"></textarea>
            <input id="id_sender" name="sender" type="hidden" value="{{ user.pk }}">
            <input id="id_receiver" name="receiver" type="hidden" value="{{ friend.pk }}">
        <p><input type="submit" value="Send a message" class="btn btn-success">
    </form>
{% endblock content %}

social/apps/core/templates/core/messages_list.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block head_title %}
    Messages
{% endblock head_title  %}

{% block extra_head_js %}
    <script type="text/javascript" src="{% static 'js/libs/jquery.shorten.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".message-text").shorten();
        });
    </script>
{% endblock extra_head_js %}

{% block content %}
    {% if not messages%}
        <h3><i>Really?</i> Go and post a message for your friend.</h3>
    {% endif %}
    {% for message in messages %}
        <div class="row-fluid">

                {% if message.sender == user %}
                    <div class="span3">
                        <img src="{{ MEDIA_URL }}/{{ message.receiver.get_profile.avatar }}" class="img-polaroid">
                    </div>
                    <div class="offset1 span8">
                    <p class="text-info">Outgoing message to <br> <a href="{% url 'profile_page' message.receiver.pk %}">
                        {{ message.receiver.first_name }} {{ message.receiver.last_name }}
                    </a>
                {% else %}
                    <div class="span3">
                        <img src="{{ MEDIA_URL }}/{{ message.sender.get_profile.avatar }}" class="img-polaroid">
                    </div>
                    <div class="offset1 span8">
                    <p class="text-success">Incoming message from <br> <a href="{% url 'profile_page' message.sender.pk %}">
                        {{ message.sender.first_name }} {{ message.sender.last_name }}
                     </a>
                {% endif %}
                <br><i>at {{ message.timestamp }}</i>
                <blockquote>
                    <p class="message-text">{{ message.text }}</p>
                </blockquote>
                {% if message.sender == user %}
                    <a href="{% url 'message_write_page' message.receiver.pk %}" class="btn">Send one more</a>
                {% else %}
                    <a href="{% url 'message_write_page' message.sender.pk %}" class="btn">Reply</a>
                {% endif %}
            </div>
         </div>
        <br/><br/>
    {% endfor %}

{% endblock content %}

social/apps/core/templates/core/profile.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}Profile{% endblock %}

{% block content %}
    <div class="row-fluid">
        <div class="span4" style="text-align: center;">
            <img src="{{ MEDIA_URL }}/{{ socialprofile.avatar }}" class="img-polaroid">
            <br/><br/>
            {% if socialprofile.user != user %}
                {% if socialprofile in user.get_profile.friends.all %}
                    <a href="{% url 'message_write_page' socialprofile.user.pk %}" class="btn btn-success">Send a message</a>
                {% else %}
                    <form action="{% url 'friends_manipulation' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{ socialprofile.user.pk }}">
                        <input class="btn btn-success" type="submit" name="add" value="Add friend" style="width: 100%;">
                    </form>
                {% endif %}
            {% else %}
                It is You!
            {% endif %}
            <hr>
        </div>
        <div class="span6 offset1">
            {% if socialprofile.user == user %}
                <div class="pull-right">
                    <a href="{% url 'profile_edit_page' %}">edit</a>
                </div>
            {% endif %}
            <legend>{{ socialprofile.user.first_name }} {{ socialprofile.user.last_name }}</legend>
            <table style="width: 100%">
                <tr>
                    <td>Born at:</td><td><span class="muted">{{ socialprofile.date_of_birth }}</span></td>
                </tr>
                <tr>
                    <td>Home town:</td><td><span class="muted">{{ socialprofile.home_town }}</span></td>
                </tr>
                <tr>
                    <td>Phone:</td><td><span class="muted">{{ socialprofile.phone_number }}</span></td>
                </tr>
                <tr>
                    <td>Skype:</td><td><span class="muted">{{ socialprofile.skype_id }}</span></td>
                <tr/>
            </table>
        </div>
    </div>
    <div class="row-fluid wallposts">
        <div class="span12">
            <ul class="thumbnails">
                <li class="span12">
                        <form action="" method="post">
                            {% csrf_token %}
                            <p><label id_for="id_text">Post something cheezy!</label>
                            <p><textarea class="input-block-level" id="id_text" name="text" rows="4"></textarea>
                            <input id="id_sender" name="sender" type="hidden" value="{{ user.pk }}">
                            <input id="id_receiver" name="receiver" type="hidden" value="{{ socialprofile.user.pk }}">
                            <p><input type="submit" value="Post wallpost" class="btn btn-success">
                        </form>
                </li>
            </ul>

            {% if wallposts %}
                {% for post in wallposts %}
                    <ul class="thumbnails">
                        <li class="span12">
                            <div class="thumbnail">
                                <h3>Post by {{ post.sender.first_name }} {{ post.sender.last_name }}</h3>
                                <i>at {{ post.timestamp }}</i>

                                <p>{{ post.text }}<a class="pull-right" href="#">Like</a></p>

                            </div>
                        </li>
                    </ul>
                {% endfor %}
            {% else %}
                No wall posts yet
            {% endif %}

        </div>
    </div>
{% endblock content %}

social/apps/core/templates/core/profile_edit.html
{% extends 'base.html' %}

{% block extra_head_js %}
    <script src="{{ STATIC_URL }}/js/profile_edit.js"></script>
{% endblock %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <legend>Edit profile information</legend>
<div class="row-fluid">
    <div class="span4" style="text-align: center;">
        <img src="{{ MEDIA_URL }}{{ form.instance.avatar }}" class="img-polaroid">
        {{ form.avatar }}
        {% if form.avatar.errors %}
            Avatar - {{ form.avatar.errors }}
        {% endif %}
    </div>
    <div class="span6 offset1">

        <label class="control-label">Your name & last name:</label>
            {% if form.name.errors %}
        <div class="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Name - {{ form.name.errors }}
        </div>
            {% endif %}
            {% if form.last_name.errors %}
        <div class="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Last Name - {{ form.name.errors }}
        </div>

            {% endif %}
            <div class="controls controls-row">{{ form.name }} {{ form.last_name }}</div>
        <br/>
        <table style="width: 100%">
            {% if form.date_of_birth.errors %}
                <tr><td colspan="2">
                    <div class="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        Born at - {{ form.date_of_birth.errors }}
                    </div>

                </td></tr>
            {% endif %}
            <tr>
                <td>Born at:</td><td><span class="muted">{{ form.date_of_birth }}</span></td>
            </tr>
            <tr>
                <td>Home town:</td><td><span class="muted">{{ form.home_town }}</span></td>
            </tr>
            <tr>
                <td>Phone:</td><td><span class="muted">{{ form.phone_number }}</span></td>
            </tr>
            <tr>
                <td>Skype:</td><td><span class="muted">{{ form.skype_id }}</span></td>
            <tr/>
        </table>
    </div>
</div>
    <div class="form-actions">
        <button type="button" class="btn">Cancel</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>
{% endblock content %}

social/apps/core/templates/core/register.html
{% extends 'base.html' %}

{% block head_title %}Sign Up{% endblock %}

{% block extra_head_js %}
<script src="{{ STATIC_URL }}/js/register.js"></script>
{% endblock %}

{% block content %}

<legend>Please, Sign Up!</legend>
{%if form.errors %}
<div class="alert">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ form.errors }}
</div>
{% endif %}
<form action="{% url 'register_page' %}" method="POST" class="form-horizontal">
    {% csrf_token %}
    <div class="control-group">
        <label class="control-label">{{form.username.label_tag}}</label>
        <div class="controls">{{form.username}}</div>
    </div>
    <div class="control-group">
        <label class="control-label">{{form.password1.label_tag}}</label>
        <div class="controls">{{form.password1}}</div>
    </div>
    <div class="control-group">
        <label class="control-label">{{form.password2.label_tag}}</label>
        <div class="controls">{{form.password2}}</div>
    </div>
    <div class="control-group">
        <div class="controls">
            <input class="btn btn-primary" type="submit" id="submit" name="submit" value="Sign up" />
            <input type="hidden" name="next" value="/" />
            or <a href="{% url 'login_page' %}">login</a>
        </div>
    </div>
</form>

{% endblock content %}

social/apps/core/templates/core/search_friends.html
{% extends 'base.html' %}
{% block head_title %}
    Search friends
{% endblock head_title  %}
{% block content %}
    <form class="form-search" method="get" action=".">
        <input type="text" class="input-medium search-query" name="q" value="{% if q %}{{ q }}{% endif %}">
        <button type="submit" class="btn">Search</button>
    </form>
    {% if q %}
        {% if found %}
            {% for man in found %}
                <div class="row-fluid">
                    <div class="span4">
                        <img src="{{ MEDIA_URL }}/{{ man.get_profile.avatar }}" class="img-polaroid">
                    </div>
                    <div class="span8">
                        <p><a href="{% url 'profile_page' man.pk %}"><h4>{{ man.first_name }} {{ man.last_name }}</h4></a></p>
                        <p>Born at: {{ man.get_profile.date_of_birth }}</p>
                        <p>Home town: {{ man.get_profile.home_town }}</p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <i>Nothing found</i>
        {% endif %}
    {% endif %}


{% endblock content %}